name: Node.js CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    - name: Setup Node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run Contract Tests
      env:
        API: http://127.0.0.1:8080
      run: npm run test:contract
